name: Colosseum Tests
on: [pull_request]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install Criterion
        run: sudo apt install -y libcriterion-dev
      - name: Run Criterion Tests
        run: make test

